### ISSUE TITLE
Accepting contributors?

### ISSUE THREAD

**Issue by JonDDowns** [hendersontrent/GAM.jl#17]
Hello,

Sorry if this is the wrong format to reach out. I am interested in contributing to the project. My background: I have an MPH in epidemiology, and I have been working with excess mortality time series models for the past 1+ year (R, GLM and mgcv packages). I have a master's in epidemiology but am taking coursework to apply for biostatistics PhD programs. I've developed proprietary packages for my organization, but I would be new to contributing to modeling packages. Thanks for your work on this package, and I would like to contribute in any way that I can.

-Jon

**Comment by hendersontrent** [comment]
Hi @JonDDowns , yes please feel free to contribute! I started this as a project over Christmas but have not had a chance to continue work on it (so the package does not currently run). Please feel free to contribute wherever! The progress made in #14 is probably best to check out first. Thanks :)
