### ISSUE TITLE
StatsPlots is a required dependency

### ISSUE THREAD

**Issue by rikhuijzer** [hendersontrent/GAM.jl#34]
When a heavy package like StatsPlots is a required dependency, then GAM is more difficult to use since StatsPlots or it's many dependencies might conflict with other packages. It's probably better to make it an optional dependency or move the plotting functions to a separate package

**Comment by hendersontrent** [comment]
Good suggestion. Will consider in the next PR.

**Comment by hendersontrent** [comment]
Have now moved plotting and other functionality to the newly created (and not yet functional) [`GAMTools.jl`](https://github.com/hendersontrent/GAMTools.jl)
